"""Self-hosted fonts for the site (faster first paint than loading them from Google Fonts).

  python tools/fonts.py      — run after `node tools/build.mjs` when new Material Symbols icons are used,
                               then run the build again (it inlines src/fonts.css into every page).

Downloads into assets/fonts/:
  * Nunito (variable, 500–900) and Caveat (600–700): latin, latin-ext, cyrillic subsets only
  * Material Symbols Rounded, reduced to the icons the site actually uses (a few KB instead of ~300 KB)
Writes src/fonts.css with @font-face rules pointing to /assets/fonts/.
"""
import glob, os, re, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "fonts")
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36"
SUBSETS = ("latin", "latin-ext", "cyrillic")
# icons that only appear at runtime (JS state switches) or in CSS ::before content
EXTRA_ICONS = {"close", "menu", "light_mode", "dark_mode", "visibility", "visibility_off", "home", "play_circle",
               "video_library", "shield_person", "check", "cancel", "check_circle", "record_voice_over",
               "chevron_right", "arrow_downward", "keyboard_arrow_up", "brush", "abc", "forest", "rocket_launch"}


def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=60).read()


def used_icons():
    icons = set(EXTRA_ICONS)
    files = glob.glob(os.path.join(ROOT, "*.html")) + glob.glob(os.path.join(ROOT, "*", "**", "*.html"), recursive=True)
    for f in files:
        if os.sep + "node_modules" + os.sep in f:
            continue
        t = open(f, encoding="utf-8").read()
        icons |= set(re.findall(r'class="[^"]*\bms\b[^"]*"[^>]*>([a-z0-9_]+)<', t))
    for f in glob.glob(os.path.join(ROOT, "assets", "js", "*.js")) + [os.path.join(ROOT, "src", "posts.js")]:
        t = open(f, encoding="utf-8").read()
        icons |= set(re.findall(r'ms">([a-z0-9_]+)<', t))
    return sorted(i for i in icons if re.fullmatch(r"[a-z][a-z0-9_]+", i))


def localize(css, prefix, keep_subsets):
    """keep the wanted @font-face blocks, download their files, point src to /assets/fonts/"""
    out = []
    for comment, block in re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css) or [("", b) for b in re.findall(r"@font-face\s*\{[^}]*\}", css)]:
        if keep_subsets and comment not in keep_subsets:
            continue
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)
        name = f"{prefix}-{comment or 'icons'}.woff2"
        path = os.path.join(OUT, name)
        data = get(url)
        open(path, "wb").write(data)
        print(f"  {name}: {len(data) // 1024} KB")
        out.append(block.replace(url, f"/assets/fonts/{name}"))
    return out


def main():
    os.makedirs(OUT, exist_ok=True)
    blocks = []
    print("Nunito")
    blocks += localize(get("https://fonts.googleapis.com/css2?family=Nunito:wght@500..900&display=swap").decode(), "nunito", SUBSETS)
    print("Caveat")
    blocks += localize(get("https://fonts.googleapis.com/css2?family=Caveat:wght@600..700&display=swap").decode(), "caveat", SUBSETS)
    icons = used_icons()
    print(f"Material Symbols Rounded: {len(icons)} icons")
    ms = get("https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,500,1,0"
             "&icon_names=" + ",".join(icons) + "&display=block").decode()
    blocks += localize(ms, "material-symbols", None)
    # keep Google's .material-symbols-rounded class rules out: the site styles .ms itself
    css = "/* generated by tools/fonts.py — do not edit */\n" + "\n".join(b.strip() for b in blocks) + "\n"
    open(os.path.join(ROOT, "src", "fonts.css"), "w", encoding="utf-8").write(css)
    print("wrote src/fonts.css")


if __name__ == "__main__":
    main()
